spring.application.name=workflow-service

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# Workflow input
messaging.queue.workflow-events=workflow.events.queue

# Workflow output
messaging.exchange.commands=domain.commands

messaging.routing-key.update-order-status=order.status.update
messaging.routing-key.process-payment=payment.process
messaging.routing-key.prepare-order=preparation.prepare
messaging.routing-key.reject-order=order.reject
messaging.routing-key.complete-order=order.complete

# Outbox Scheduler
outbox.scheduler.fixed-delay=5000